---
# roles/launch/tasks/main.yml

- name: search for latest CentOS AMI
  ec2_ami_find:
    aws_access_key: '{{ ami_access }}'
    aws_secret_key: '{{ ami_secret }}'
    region: "{{ region }}"
    architecture: x86_64
    name: CentOS Linux 7*EBS*
    owner: 679593333241
    sort: creationDate
    sort_order: descending
    sort_end: 1
    no_result_action: fail
  register: ami_result

- name: Launch new instance
  ec2:
    aws_access_key: '{{ ami_access }}'
    aws_secret_key: '{{ ami_secret }}'
    region: "{{ region }}"
    keypair: "{{ keypair }}"
    zone: "{{ zone }}"
    group: "{{ security_groups }}"
    image: "{{ ami_result.results[0].ami_id }}"
    instance_type: "{{ instance_type }}"
    instance_tags:
      Name: "{{ name }}"
    volumes: "{{ volumes }}"
    wait: yes
  register: ec2

- name: Add new instances to host group
  add_host:
    name: "{{ item.public_dns_name }}"
    groups: "{{ name }}"
    ec2_id: "{{ item.id }}"
  with_items: '{{ec2.instances}}'
#  with_items: ec2.instances

- name: Wait for instance to boot
  wait_for:
    host: "{{ item.public_dns_name }}"
    port: 22
    delay: 30
    timeout: 320
    state: started
  with_items: '{{ec2.instances}}'
